### ISSUE TITLE
change query names

### ISSUE THREAD

**Issue by Palashio** [Palashio/libra#10]
some of the queries like `regression_querry_ann` are quite tacky, a system for naming queries needs to be made.

**Comment by vyathakavilocana** [comment]
If we were to work on approaching this problem, would it be okay for us to first come up with a naming convention on a separate file documenting the new protocol and upload for reference before making any changes?

**Comment by Palashio** [comment]
This issue is for the future; not something we should worry about right now. My bad for not specifying.
