### ISSUE TITLE
Occasional wrong selection of layers 

### ISSUE THREAD

**Issue by aliaryan** [Palashio/libra#269]
I am using Libra on Google Colab. After the V1.0.1 release I notice occasional wrong selection of layers in Neural net. Sometimes when I run it on a particular dataset it stops at the initial number of layer .i.e. 3. But when I run it again then it takes the right number of layers, which in my case is 7. But this problem is occasional and most probably happens when I run it for the first time. I have attached the screenshots as a reference.
![Screenshot 2020-07-19 at 11 32 00 AM](https://user-images.githubusercontent.com/31564091/87868555-ad7a6f80-c9b4-11ea-819c-3bc1702feba2.png)
![Screenshot 2020-07-19 at 11 36 01 AM](https://user-images.githubusercontent.com/31564091/87868557-afdcc980-c9b4-11ea-947d-18659e982f8b.png)

**Comment by Palashio** [comment]
hi @aliaryan this has been fixed. we'll release 1.0.2 soon.
