### ISSUE TITLE
No plots visible while using client_object.plots()

### ISSUE THREAD

**Issue by aliaryan** [Palashio/libra#294]
I am using Libra on Colab. I did try using client_object.plots() but I couldn't see the plots. Moreover I also used %matplotlib inline, But it was of no help. I have attached screenshot as a reference.
![Screenshot 2020-07-21 at 11 25 20 AM](https://user-images.githubusercontent.com/31564091/88018337-29a3bd00-cb45-11ea-82b4-95633dbc1d22.png)

**Comment by Palashio** [comment]
So, `plots()` isn't designed to display all the plots. It returns the plots dictionary. To display a plot you can do `newClient.plots()['plot_name`]`.
