### ISSUE TITLE
CNN Data Parameters

### ISSUE THREAD

**Issue by anas-awadalla** [Palashio/libra#32]
Most image data sets consist of a CSV file with image path and labels as well as an overall image folder. Currently, the need to enter a path for every class seems redundant and might be difficult for most large image datasets. We might want to accept a CSV and Image directory path.

**Comment by Palashio** [comment]
i think this is a really good point.

We just need to make the CNN query handle all sorts of data inputs. Like you said, a csv file and folders and/or just seperate folders. This all has to be handled automatically.
