### ISSUE TITLE
Adding support for more pretrained models

### ISSUE THREAD

**Issue by sukkritsharmaofficial** [Palashio/libra#352]
I can help you out with adding support to more pre-trained models which are usually considered while training an image classifier 

**Light Weight models like:**

- All versions of MobileNet (V1,V2,.. )

**Substantially Deeper Models like:**

- All versions of Densenet (121,169,201)
- InceptionV3
- InceptionResNetV3
 
Adding support for these will give the users a wide variety while selecting the architectures that they need to train on depending upon their specific use case 💯

**Comment by DaMLGuy** [comment]
I find this PR very misleading ,there is nothing called as "Deeper models" and "Lightweight models".The  key  difference is with respect to the number of parameters a model is using.What i inferred from this you are just trying to copy and paste the model weights that are provided by keras .If that is so any kind of DCNN models can be added without taking in account.

**Comment by sukkritsharmaofficial** [comment]
Firstly its not a PR, its just an issue that I've raised, but since you have joined Github half an hour back I can understand your confusion. 
Talking about the issue raised, since obviously you haven't used the Library as such and have not gone through the whole code, you wouldn't understand that this library uses models from keras and while training your model you are given two choices, one is to use pretrained models with weights from imagenet or custom weights or using a custom architecture defined in a json file. But since they had added very less number of models as of now, I have raised this issue. Its anyways better than editing ReadMe and calling it as a PR.

**Comment by Palashio** [comment]
this is not the place the quarrel. on the other hand @sukkritsharmaofficial that sounds good!

**Comment by Palashio** [comment]
By the way, if you've got any questions about implementation etc. you can join the slack channel and PM me.

**Comment by sukkritsharmaofficial** [comment]
@Palashio yeah sure, i'll hit you up there!
