### ISSUE TITLE
[bug] Dashboard does not display -- streamlit error

### ISSUE THREAD

**Issue by willeppy** [Palashio/libra#361]
**Describe the bug**
Dashboard does not display when client.dashboard() is called. A streamlit error occurs.

**To Reproduce**
1. pip install libra (version is 1.1.2)
2. pip install streamlit (for some reason didn't install even though I saw it in requirements.txt. Local version is 0.67.0 )
3. Ran the following code:
```python
from libra import client

client1 = client("data/housing.csv") #UCI housing dataset from the Libra example
client1.decision_tree_query("model ocean proximity")
client1.analyze()
# above all worked fine

client1.dashboard() # ISSUE HERE: does not show dashboard
```

**Expected behavior**
Expected a dashboard to show. 

**Error**
Nothing shows in my Jupyter output. The following shows up in my terminal. I tried running the above code from both Jupyter or just python in command line and got error both times.

<img width="379" alt="Screen Shot 2020-09-21 at 6 34 25 PM" src="https://user-images.githubusercontent.com/13400543/93828530-9157b080-fc39-11ea-84b1-aaeb895755a2.png">

**Device**
 - OS: macOS Catalina 10.15.6
 - Browser: jupyter in safari

**Comment by anas-awadalla** [comment]
Hey @willeppy  I tested your code and this does seem to be an issue. It might take a bit to fix so here is how you can overcome that for now. First, install the master branch by running "pip install git+https://github.com/Palashio/libra.git". Then add the following python file to your current directory [https://github.com/Palashio/libra/blob/master/libra/dashboard/LibEDA.py](url). This should let you run the dashboard! I will update this issue once I fix the bug.

Thanks!
